/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api;

import com.skyflow.api.core.ClientOptions;
import com.skyflow.api.core.Suppliers;
import com.skyflow.api.resources.flowservice.FlowserviceClient;
import com.skyflow.api.resources.records.RecordsClient;

import java.util.function.Supplier;

public class ApiClient {
    protected final ClientOptions clientOptions;

    private final RawApiClient rawClient;

    protected final Supplier<RecordsClient> recordsClient;

    protected final Supplier<FlowserviceClient> flowserviceClient;

    public ApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawApiClient(clientOptions);
        this.recordsClient = Suppliers.memoize(() -> new RecordsClient(clientOptions));
        this.flowserviceClient = Suppliers.memoize(() -> new FlowserviceClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawApiClient withRawResponse() {
        return this.rawClient;
    }

    public RecordsClient records() {
        return this.recordsClient.get();
    }

    public FlowserviceClient flowservice() {
        return this.flowserviceClient.get();
    }

    public static ApiClientBuilder builder() {
        return new ApiClientBuilder();
    }
}
