/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api;

import com.skyflow.api.core.ClientOptions;
import com.skyflow.api.core.Suppliers;
import com.skyflow.api.resources.flowservice.AsyncFlowserviceClient;
import com.skyflow.api.resources.records.AsyncRecordsClient;

import java.util.function.Supplier;

public class AsyncApiClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawApiClient rawClient;

    protected final Supplier<AsyncRecordsClient> recordsClient;

    protected final Supplier<AsyncFlowserviceClient> flowserviceClient;

    public AsyncApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawApiClient(clientOptions);
        this.recordsClient = Suppliers.memoize(() -> new AsyncRecordsClient(clientOptions));
        this.flowserviceClient = Suppliers.memoize(() -> new AsyncFlowserviceClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawApiClient withRawResponse() {
        return this.rawClient;
    }

    public AsyncRecordsClient records() {
        return this.recordsClient.get();
    }

    public AsyncFlowserviceClient flowservice() {
        return this.flowserviceClient.get();
    }

    public static AsyncApiClientBuilder builder() {
        return new AsyncApiClientBuilder();
    }
}
