/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api;

import com.skyflow.api.core.ClientOptions;

public class AsyncRawApiClient {
    protected final ClientOptions clientOptions;

    public AsyncRawApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }
}
