/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api;

import com.skyflow.api.core.ClientOptions;

public class RawApiClient {
    protected final ClientOptions clientOptions;

    public RawApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }


}
