/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.resources.records;

import com.skyflow.api.core.ClientOptions;
import com.skyflow.api.core.RequestOptions;
import com.skyflow.api.resources.records.requests.V1ExecuteQueryRequest;
import com.skyflow.api.types.V1ExecuteQueryResponse;

import java.util.concurrent.CompletableFuture;

public class AsyncRecordsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawRecordsClient rawClient;

    public AsyncRecordsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRecordsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRecordsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Executes a query on the specified vault.
     */
    public CompletableFuture<V1ExecuteQueryResponse> flowServiceExecuteQuery() {
        return this.rawClient.flowServiceExecuteQuery().thenApply(response -> response.body());
    }

    /**
     * Executes a query on the specified vault.
     */
    public CompletableFuture<V1ExecuteQueryResponse> flowServiceExecuteQuery(V1ExecuteQueryRequest request) {
        return this.rawClient.flowServiceExecuteQuery(request).thenApply(response -> response.body());
    }

    /**
     * Executes a query on the specified vault.
     */
    public CompletableFuture<V1ExecuteQueryResponse> flowServiceExecuteQuery(
            V1ExecuteQueryRequest request, RequestOptions requestOptions) {
        return this.rawClient.flowServiceExecuteQuery(request, requestOptions).thenApply(response -> response.body());
    }
}
