/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.resources.records;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.skyflow.api.core.*;
import com.skyflow.api.resources.records.requests.V1ExecuteQueryRequest;
import com.skyflow.api.types.V1ExecuteQueryResponse;
import okhttp3.*;

import java.io.IOException;

public class RawRecordsClient {
    protected final ClientOptions clientOptions;

    public RawRecordsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Executes a query on the specified vault.
     */
    public ApiClientHttpResponse<V1ExecuteQueryResponse> flowServiceExecuteQuery() {
        return flowServiceExecuteQuery(V1ExecuteQueryRequest.builder().build());
    }

    /**
     * Executes a query on the specified vault.
     */
    public ApiClientHttpResponse<V1ExecuteQueryResponse> flowServiceExecuteQuery(V1ExecuteQueryRequest request) {
        return flowServiceExecuteQuery(request, null);
    }

    /**
     * Executes a query on the specified vault.
     */
    public ApiClientHttpResponse<V1ExecuteQueryResponse> flowServiceExecuteQuery(
            V1ExecuteQueryRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v2/query")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ApiClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new ApiClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), V1ExecuteQueryResponse.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new ApiClientApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new ApiClientException("Network error executing HTTP request", e);
        }
    }
}
