/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.resources.records;

import com.skyflow.api.core.ClientOptions;
import com.skyflow.api.core.RequestOptions;
import com.skyflow.api.resources.records.requests.V1ExecuteQueryRequest;
import com.skyflow.api.types.V1ExecuteQueryResponse;

public class RecordsClient {
    protected final ClientOptions clientOptions;

    private final RawRecordsClient rawClient;

    public RecordsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawRecordsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawRecordsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Executes a query on the specified vault.
     */
    public V1ExecuteQueryResponse flowServiceExecuteQuery() {
        return this.rawClient.flowServiceExecuteQuery().body();
    }

    /**
     * Executes a query on the specified vault.
     */
    public V1ExecuteQueryResponse flowServiceExecuteQuery(V1ExecuteQueryRequest request) {
        return this.rawClient.flowServiceExecuteQuery(request).body();
    }

    /**
     * Executes a query on the specified vault.
     */
    public V1ExecuteQueryResponse flowServiceExecuteQuery(
            V1ExecuteQueryRequest request, RequestOptions requestOptions) {
        return this.rawClient.flowServiceExecuteQuery(request, requestOptions).body();
    }
}
