/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.common.errors;

import com.skyflow.common.core.ApiClientApiException;
import java.util.Map;
import okhttp3.Response;

public final class UnauthorizedError extends ApiClientApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Map<String, Object> body;

    public UnauthorizedError(Map<String, Object> body) {
        super("UnauthorizedError", 401, body);
        this.body = body;
    }

    public UnauthorizedError(Map<String, Object> body, Response rawResponse) {
        super("UnauthorizedError", 401, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Map<String, Object> body() {
        return this.body;
    }
}
