/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.common;

import com.skyflow.common.core.ClientOptions;
import com.skyflow.common.core.Suppliers;
import com.skyflow.common.resources.authentication.AuthenticationClient;
import java.util.function.Supplier;

public class ApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AuthenticationClient> authenticationClient;

    public ApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.authenticationClient = Suppliers.memoize(() -> new AuthenticationClient(clientOptions));
    }

    public AuthenticationClient authentication() {
        return this.authenticationClient.get();
    }

    public static ApiClientBuilder builder() {
        return new ApiClientBuilder();
    }
}
