/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.resources.records.requests;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1ExecuteQueryRequest.Builder.class)
public final class V1ExecuteQueryRequest {
    private final Optional<String> vaultId;

    private final Optional<String> query;

    private final Map<String, Object> additionalProperties;

    private V1ExecuteQueryRequest(
            Optional<String> vaultId, Optional<String> query, Map<String, Object> additionalProperties) {
        this.vaultId = vaultId;
        this.query = query;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID of the vault where data is being inserted
     */
    @JsonProperty("vaultID")
    public Optional<String> getVaultId() {
        return vaultId;
    }

    /**
     * @return Query to execute.
     */
    @JsonProperty("query")
    public Optional<String> getQuery() {
        return query;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1ExecuteQueryRequest && equalTo((V1ExecuteQueryRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1ExecuteQueryRequest other) {
        return vaultId.equals(other.vaultId) && query.equals(other.query);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.vaultId, this.query);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> vaultId = Optional.empty();

        private Optional<String> query = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(V1ExecuteQueryRequest other) {
            vaultId(other.getVaultId());
            query(other.getQuery());
            return this;
        }

        @JsonSetter(value = "vaultID", nulls = Nulls.SKIP)
        public Builder vaultId(Optional<String> vaultId) {
            this.vaultId = vaultId;
            return this;
        }

        public Builder vaultId(String vaultId) {
            this.vaultId = Optional.ofNullable(vaultId);
            return this;
        }

        @JsonSetter(value = "query", nulls = Nulls.SKIP)
        public Builder query(Optional<String> query) {
            this.query = query;
            return this;
        }

        public Builder query(String query) {
            this.query = Optional.ofNullable(query);
            return this;
        }

        public V1ExecuteQueryRequest build() {
            return new V1ExecuteQueryRequest(vaultId, query, additionalProperties);
        }
    }
}
