/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.resources.flowservice.requests;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1DeleteRequest.Builder.class)
public final class V1DeleteRequest {
    private final Optional<String> vaultId;

    private final Optional<String> tableName;

    private final Optional<List<String>> skyflowIDs;

    private final Map<String, Object> additionalProperties;

    private V1DeleteRequest(
            Optional<String> vaultId,
            Optional<String> tableName,
            Optional<List<String>> skyflowIDs,
            Map<String, Object> additionalProperties) {
        this.vaultId = vaultId;
        this.tableName = tableName;
        this.skyflowIDs = skyflowIDs;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID of the vault where data is being deleted
     */
    @JsonProperty("vaultID")
    public Optional<String> getVaultId() {
        return vaultId;
    }

    /**
     * @return Name of the table where data is being deleted
     */
    @JsonProperty("tableName")
    public Optional<String> getTableName() {
        return tableName;
    }

    /**
     * @return Skyflow ID for the record to be deleted
     */
    @JsonProperty("skyflowIDs")
    public Optional<List<String>> getSkyflowIDs() {
        return skyflowIDs;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1DeleteRequest && equalTo((V1DeleteRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1DeleteRequest other) {
        return vaultId.equals(other.vaultId)
                && tableName.equals(other.tableName)
                && skyflowIDs.equals(other.skyflowIDs);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.vaultId, this.tableName, this.skyflowIDs);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> vaultId = Optional.empty();

        private Optional<String> tableName = Optional.empty();

        private Optional<List<String>> skyflowIDs = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(V1DeleteRequest other) {
            vaultId(other.getVaultId());
            tableName(other.getTableName());
            skyflowIDs(other.getSkyflowIDs());
            return this;
        }

        @JsonSetter(value = "vaultID", nulls = Nulls.SKIP)
        public Builder vaultId(Optional<String> vaultId) {
            this.vaultId = vaultId;
            return this;
        }

        public Builder vaultId(String vaultId) {
            this.vaultId = Optional.ofNullable(vaultId);
            return this;
        }

        @JsonSetter(value = "tableName", nulls = Nulls.SKIP)
        public Builder tableName(Optional<String> tableName) {
            this.tableName = tableName;
            return this;
        }

        public Builder tableName(String tableName) {
            this.tableName = Optional.ofNullable(tableName);
            return this;
        }

        @JsonSetter(value = "skyflowIDs", nulls = Nulls.SKIP)
        public Builder skyflowIDs(Optional<List<String>> skyflowIDs) {
            this.skyflowIDs = skyflowIDs;
            return this;
        }

        public Builder skyflowIDs(List<String> skyflowIDs) {
            this.skyflowIDs = Optional.ofNullable(skyflowIDs);
            return this;
        }

        public V1DeleteRequest build() {
            return new V1DeleteRequest(vaultId, tableName, skyflowIDs, additionalProperties);
        }
    }
}
