/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.resources.flowservice.requests;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;
import com.skyflow.api.types.V1TokenGroupRedactions;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1DetokenizeRequest.Builder.class)
public final class V1DetokenizeRequest {
    private final Optional<String> vaultId;

    private final Optional<List<String>> tokens;

    private final Optional<List<V1TokenGroupRedactions>> tokenGroupRedactions;

    private final Map<String, Object> additionalProperties;

    private V1DetokenizeRequest(
            Optional<String> vaultId,
            Optional<List<String>> tokens,
            Optional<List<V1TokenGroupRedactions>> tokenGroupRedactions,
            Map<String, Object> additionalProperties) {
        this.vaultId = vaultId;
        this.tokens = tokens;
        this.tokenGroupRedactions = tokenGroupRedactions;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID of the vault where detokenizing
     */
    @JsonProperty("vaultID")
    public Optional<String> getVaultId() {
        return vaultId;
    }

    /**
     * @return Token to be detokenized
     */
    @JsonProperty("tokens")
    public Optional<List<String>> getTokens() {
        return tokens;
    }

    /**
     * @return List of token groups to be redacted.
     */
    @JsonProperty("tokenGroupRedactions")
    public Optional<List<V1TokenGroupRedactions>> getTokenGroupRedactions() {
        return tokenGroupRedactions;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1DetokenizeRequest && equalTo((V1DetokenizeRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1DetokenizeRequest other) {
        return vaultId.equals(other.vaultId)
                && tokens.equals(other.tokens)
                && tokenGroupRedactions.equals(other.tokenGroupRedactions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.vaultId, this.tokens, this.tokenGroupRedactions);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> vaultId = Optional.empty();

        private Optional<List<String>> tokens = Optional.empty();

        private Optional<List<V1TokenGroupRedactions>> tokenGroupRedactions = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(V1DetokenizeRequest other) {
            vaultId(other.getVaultId());
            tokens(other.getTokens());
            tokenGroupRedactions(other.getTokenGroupRedactions());
            return this;
        }

        @JsonSetter(value = "vaultID", nulls = Nulls.SKIP)
        public Builder vaultId(Optional<String> vaultId) {
            this.vaultId = vaultId;
            return this;
        }

        public Builder vaultId(String vaultId) {
            this.vaultId = Optional.ofNullable(vaultId);
            return this;
        }

        @JsonSetter(value = "tokens", nulls = Nulls.SKIP)
        public Builder tokens(Optional<List<String>> tokens) {
            this.tokens = tokens;
            return this;
        }

        public Builder tokens(List<String> tokens) {
            this.tokens = Optional.ofNullable(tokens);
            return this;
        }

        @JsonSetter(value = "tokenGroupRedactions", nulls = Nulls.SKIP)
        public Builder tokenGroupRedactions(Optional<List<V1TokenGroupRedactions>> tokenGroupRedactions) {
            this.tokenGroupRedactions = tokenGroupRedactions;
            return this;
        }

        public Builder tokenGroupRedactions(List<V1TokenGroupRedactions> tokenGroupRedactions) {
            this.tokenGroupRedactions = Optional.ofNullable(tokenGroupRedactions);
            return this;
        }

        public V1DetokenizeRequest build() {
            return new V1DetokenizeRequest(vaultId, tokens, tokenGroupRedactions, additionalProperties);
        }
    }
}
