/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.resources.flowservice.requests;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;
import com.skyflow.api.types.FlowEnumUpdateType;
import com.skyflow.api.types.V1UpdateRecordData;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1UpdateRequest.Builder.class)
public final class V1UpdateRequest {
    private final Optional<String> vaultId;

    private final Optional<String> tableName;

    private final Optional<List<V1UpdateRecordData>> records;

    private final Optional<FlowEnumUpdateType> updateType;

    private final Map<String, Object> additionalProperties;

    private V1UpdateRequest(
            Optional<String> vaultId,
            Optional<String> tableName,
            Optional<List<V1UpdateRecordData>> records,
            Optional<FlowEnumUpdateType> updateType,
            Map<String, Object> additionalProperties) {
        this.vaultId = vaultId;
        this.tableName = tableName;
        this.records = records;
        this.updateType = updateType;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID of the vault where data is being updated
     */
    @JsonProperty("vaultID")
    public Optional<String> getVaultId() {
        return vaultId;
    }

    /**
     * @return Name of the table where data is being updated
     */
    @JsonProperty("tableName")
    public Optional<String> getTableName() {
        return tableName;
    }

    /**
     * @return List of data row wise that is to be updated in the vault
     */
    @JsonProperty("records")
    public Optional<List<V1UpdateRecordData>> getRecords() {
        return records;
    }

    @JsonProperty("updateType")
    public Optional<FlowEnumUpdateType> getUpdateType() {
        return updateType;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1UpdateRequest && equalTo((V1UpdateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1UpdateRequest other) {
        return vaultId.equals(other.vaultId)
                && tableName.equals(other.tableName)
                && records.equals(other.records)
                && updateType.equals(other.updateType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.vaultId, this.tableName, this.records, this.updateType);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> vaultId = Optional.empty();

        private Optional<String> tableName = Optional.empty();

        private Optional<List<V1UpdateRecordData>> records = Optional.empty();

        private Optional<FlowEnumUpdateType> updateType = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(V1UpdateRequest other) {
            vaultId(other.getVaultId());
            tableName(other.getTableName());
            records(other.getRecords());
            updateType(other.getUpdateType());
            return this;
        }

        @JsonSetter(value = "vaultID", nulls = Nulls.SKIP)
        public Builder vaultId(Optional<String> vaultId) {
            this.vaultId = vaultId;
            return this;
        }

        public Builder vaultId(String vaultId) {
            this.vaultId = Optional.ofNullable(vaultId);
            return this;
        }

        @JsonSetter(value = "tableName", nulls = Nulls.SKIP)
        public Builder tableName(Optional<String> tableName) {
            this.tableName = tableName;
            return this;
        }

        public Builder tableName(String tableName) {
            this.tableName = Optional.ofNullable(tableName);
            return this;
        }

        @JsonSetter(value = "records", nulls = Nulls.SKIP)
        public Builder records(Optional<List<V1UpdateRecordData>> records) {
            this.records = records;
            return this;
        }

        public Builder records(List<V1UpdateRecordData> records) {
            this.records = Optional.ofNullable(records);
            return this;
        }

        @JsonSetter(value = "updateType", nulls = Nulls.SKIP)
        public Builder updateType(Optional<FlowEnumUpdateType> updateType) {
            this.updateType = updateType;
            return this;
        }

        public Builder updateType(FlowEnumUpdateType updateType) {
            this.updateType = Optional.ofNullable(updateType);
            return this;
        }

        public V1UpdateRequest build() {
            return new V1UpdateRequest(vaultId, tableName, records, updateType, additionalProperties);
        }
    }
}
