/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.resources.recordservice.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.vaultLH.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeleteTokenRequest.Builder.class)
public final class DeleteTokenRequest {
    private final Optional<String> vaultId;

    private final Optional<List<String>> tokens;

    private final Map<String, Object> additionalProperties;

    private DeleteTokenRequest(
            Optional<String> vaultId, Optional<List<String>> tokens, Map<String, Object> additionalProperties) {
        this.vaultId = vaultId;
        this.tokens = tokens;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Vault ID
     */
    @JsonProperty("vaultID")
    public Optional<String> getVaultId() {
        return vaultId;
    }

    /**
     * @return Token value
     */
    @JsonProperty("tokens")
    public Optional<List<String>> getTokens() {
        return tokens;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeleteTokenRequest && equalTo((DeleteTokenRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeleteTokenRequest other) {
        return vaultId.equals(other.vaultId) && tokens.equals(other.tokens);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.vaultId, this.tokens);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> vaultId = Optional.empty();

        private Optional<List<String>> tokens = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DeleteTokenRequest other) {
            vaultId(other.getVaultId());
            tokens(other.getTokens());
            return this;
        }

        /**
         * <p>Vault ID</p>
         */
        @JsonSetter(value = "vaultID", nulls = Nulls.SKIP)
        public Builder vaultId(Optional<String> vaultId) {
            this.vaultId = vaultId;
            return this;
        }

        public Builder vaultId(String vaultId) {
            this.vaultId = Optional.ofNullable(vaultId);
            return this;
        }

        /**
         * <p>Token value</p>
         */
        @JsonSetter(value = "tokens", nulls = Nulls.SKIP)
        public Builder tokens(Optional<List<String>> tokens) {
            this.tokens = tokens;
            return this;
        }

        public Builder tokens(List<String> tokens) {
            this.tokens = Optional.ofNullable(tokens);
            return this;
        }

        public DeleteTokenRequest build() {
            return new DeleteTokenRequest(vaultId, tokens, additionalProperties);
        }
    }
}
