/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.resources.recordservice.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.vaultLH.core.ObjectMappers;
import com.skyflow.vaultLH.types.TokenizeRequestObject;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokenizeRequest.Builder.class)
public final class TokenizeRequest {
    private final Optional<String> vaultId;

    private final Optional<List<TokenizeRequestObject>> data;

    private final Map<String, Object> additionalProperties;

    private TokenizeRequest(
            Optional<String> vaultId,
            Optional<List<TokenizeRequestObject>> data,
            Map<String, Object> additionalProperties) {
        this.vaultId = vaultId;
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Vault ID.
     */
    @JsonProperty("vaultID")
    public Optional<String> getVaultId() {
        return vaultId;
    }

    /**
     * @return Data to be tokenized
     */
    @JsonProperty("data")
    public Optional<List<TokenizeRequestObject>> getData() {
        return data;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TokenizeRequest && equalTo((TokenizeRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TokenizeRequest other) {
        return vaultId.equals(other.vaultId) && data.equals(other.data);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.vaultId, this.data);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> vaultId = Optional.empty();

        private Optional<List<TokenizeRequestObject>> data = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TokenizeRequest other) {
            vaultId(other.getVaultId());
            data(other.getData());
            return this;
        }

        /**
         * <p>Vault ID.</p>
         */
        @JsonSetter(value = "vaultID", nulls = Nulls.SKIP)
        public Builder vaultId(Optional<String> vaultId) {
            this.vaultId = vaultId;
            return this;
        }

        public Builder vaultId(String vaultId) {
            this.vaultId = Optional.ofNullable(vaultId);
            return this;
        }

        /**
         * <p>Data to be tokenized</p>
         */
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(Optional<List<TokenizeRequestObject>> data) {
            this.data = data;
            return this;
        }

        public Builder data(List<TokenizeRequestObject> data) {
            this.data = Optional.ofNullable(data);
            return this;
        }

        public TokenizeRequest build() {
            return new TokenizeRequest(vaultId, data, additionalProperties);
        }
    }
}
