/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.vaultLH.core.ObjectMappers;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeleteTokenResponse.Builder.class)
public final class DeleteTokenResponse {
    private final Optional<List<DeleteTokenResponseObject>> tokens;

    private final Map<String, Object> additionalProperties;

    private DeleteTokenResponse(
            Optional<List<DeleteTokenResponseObject>> tokens, Map<String, Object> additionalProperties) {
        this.tokens = tokens;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Tokens data for Delete
     */
    @JsonProperty("tokens")
    public Optional<List<DeleteTokenResponseObject>> getTokens() {
        return tokens;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeleteTokenResponse && equalTo((DeleteTokenResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeleteTokenResponse other) {
        return tokens.equals(other.tokens);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.tokens);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<DeleteTokenResponseObject>> tokens = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DeleteTokenResponse other) {
            tokens(other.getTokens());
            return this;
        }

        /**
         * <p>Tokens data for Delete</p>
         */
        @JsonSetter(value = "tokens", nulls = Nulls.SKIP)
        public Builder tokens(Optional<List<DeleteTokenResponseObject>> tokens) {
            this.tokens = tokens;
            return this;
        }

        public Builder tokens(List<DeleteTokenResponseObject> tokens) {
            this.tokens = Optional.ofNullable(tokens);
            return this;
        }

        public DeleteTokenResponse build() {
            return new DeleteTokenResponse(tokens, additionalProperties);
        }
    }
}
