/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.vaultLH.core.ObjectMappers;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DetokenizeResponse.Builder.class)
public final class DetokenizeResponse {
    private final Optional<List<DetokenizeResponseObject>> response;

    private final Map<String, Object> additionalProperties;

    private DetokenizeResponse(
            Optional<List<DetokenizeResponseObject>> response, Map<String, Object> additionalProperties) {
        this.response = response;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Detokenized data
     */
    @JsonProperty("response")
    public Optional<List<DetokenizeResponseObject>> getResponse() {
        return response;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DetokenizeResponse && equalTo((DetokenizeResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DetokenizeResponse other) {
        return response.equals(other.response);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.response);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<DetokenizeResponseObject>> response = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DetokenizeResponse other) {
            response(other.getResponse());
            return this;
        }

        /**
         * <p>Detokenized data</p>
         */
        @JsonSetter(value = "response", nulls = Nulls.SKIP)
        public Builder response(Optional<List<DetokenizeResponseObject>> response) {
            this.response = response;
            return this;
        }

        public Builder response(List<DetokenizeResponseObject> response) {
            this.response = Optional.ofNullable(response);
            return this;
        }

        public DetokenizeResponse build() {
            return new DetokenizeResponse(response, additionalProperties);
        }
    }
}
