/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.vaultLH.core.ObjectMappers;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InsertResponse.Builder.class)
public final class InsertResponse {
    private final Optional<List<RecordResponseObject>> records;

    private final Map<String, Object> additionalProperties;

    private InsertResponse(Optional<List<RecordResponseObject>> records, Map<String, Object> additionalProperties) {
        this.records = records;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return List of inserted records with skyflow ID, tokens, data, and any partial errors.
     */
    @JsonProperty("records")
    public Optional<List<RecordResponseObject>> getRecords() {
        return records;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InsertResponse && equalTo((InsertResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InsertResponse other) {
        return records.equals(other.records);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.records);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<RecordResponseObject>> records = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(InsertResponse other) {
            records(other.getRecords());
            return this;
        }

        /**
         * <p>List of inserted records with skyflow ID, tokens, data, and any partial errors.</p>
         */
        @JsonSetter(value = "records", nulls = Nulls.SKIP)
        public Builder records(Optional<List<RecordResponseObject>> records) {
            this.records = records;
            return this;
        }

        public Builder records(List<RecordResponseObject> records) {
            this.records = Optional.ofNullable(records);
            return this;
        }

        public InsertResponse build() {
            return new InsertResponse(records, additionalProperties);
        }
    }
}
