/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.resources.flowservice;

import com.skyflow.api.core.ClientOptions;
import com.skyflow.api.core.RequestOptions;
import com.skyflow.api.resources.flowservice.requests.*;
import com.skyflow.api.types.*;

import java.util.concurrent.CompletableFuture;

public class AsyncFlowserviceClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawFlowserviceClient rawClient;

    public AsyncFlowserviceClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawFlowserviceClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawFlowserviceClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<V1DeleteResponse> delete() {
        return this.rawClient.delete().thenApply(response -> response.body());
    }

    public CompletableFuture<V1DeleteResponse> delete(V1DeleteRequest request) {
        return this.rawClient.delete(request).thenApply(response -> response.body());
    }

    public CompletableFuture<V1DeleteResponse> delete(V1DeleteRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<V1GetResponse> get() {
        return this.rawClient.get().thenApply(response -> response.body());
    }

    public CompletableFuture<V1GetResponse> get(V1GetRequest request) {
        return this.rawClient.get(request).thenApply(response -> response.body());
    }

    public CompletableFuture<V1GetResponse> get(V1GetRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<V1InsertResponse> insert() {
        return this.rawClient.insert().thenApply(response -> response.body());
    }

    public CompletableFuture<V1InsertResponse> insert(V1InsertRequest request) {
        return this.rawClient.insert(request).thenApply(response -> response.body());
    }

    public CompletableFuture<V1InsertResponse> insert(V1InsertRequest request, RequestOptions requestOptions) {
        return this.rawClient.insert(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<V1UpdateResponse> update() {
        return this.rawClient.update().thenApply(response -> response.body());
    }

    public CompletableFuture<V1UpdateResponse> update(V1UpdateRequest request) {
        return this.rawClient.update(request).thenApply(response -> response.body());
    }

    public CompletableFuture<V1UpdateResponse> update(V1UpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<V1DetokenizeResponse> detokenize() {
        return this.rawClient.detokenize().thenApply(response -> response.body());
    }

    public CompletableFuture<V1DetokenizeResponse> detokenize(V1DetokenizeRequest request) {
        return this.rawClient.detokenize(request).thenApply(response -> response.body());
    }

    public CompletableFuture<V1DetokenizeResponse> detokenize(
            V1DetokenizeRequest request, RequestOptions requestOptions) {
        return this.rawClient.detokenize(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<V1TokenizeResponse> tokenize() {
        return this.rawClient.tokenize().thenApply(response -> response.body());
    }

    public CompletableFuture<V1TokenizeResponse> tokenize(V1TokenizeRequest request) {
        return this.rawClient.tokenize(request).thenApply(response -> response.body());
    }

    public CompletableFuture<V1TokenizeResponse> tokenize(V1TokenizeRequest request, RequestOptions requestOptions) {
        return this.rawClient.tokenize(request, requestOptions).thenApply(response -> response.body());
    }
}
