/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.resources.flowservice;

import com.skyflow.api.core.ClientOptions;
import com.skyflow.api.core.RequestOptions;
import com.skyflow.api.resources.flowservice.requests.*;
import com.skyflow.api.types.*;

public class FlowserviceClient {
    protected final ClientOptions clientOptions;

    private final RawFlowserviceClient rawClient;

    public FlowserviceClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawFlowserviceClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawFlowserviceClient withRawResponse() {
        return this.rawClient;
    }

    public V1DeleteResponse delete() {
        return this.rawClient.delete().body();
    }

    public V1DeleteResponse delete(V1DeleteRequest request) {
        return this.rawClient.delete(request).body();
    }

    public V1DeleteResponse delete(V1DeleteRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(request, requestOptions).body();
    }

    public V1GetResponse get() {
        return this.rawClient.get().body();
    }

    public V1GetResponse get(V1GetRequest request) {
        return this.rawClient.get(request).body();
    }

    public V1GetResponse get(V1GetRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).body();
    }

    public V1InsertResponse insert() {
        return this.rawClient.insert().body();
    }

    public V1InsertResponse insert(V1InsertRequest request) {
        return this.rawClient.insert(request).body();
    }

    public V1InsertResponse insert(V1InsertRequest request, RequestOptions requestOptions) {
        return this.rawClient.insert(request, requestOptions).body();
    }

    public V1UpdateResponse update() {
        return this.rawClient.update().body();
    }

    public V1UpdateResponse update(V1UpdateRequest request) {
        return this.rawClient.update(request).body();
    }

    public V1UpdateResponse update(V1UpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(request, requestOptions).body();
    }

    public V1DetokenizeResponse detokenize() {
        return this.rawClient.detokenize().body();
    }

    public V1DetokenizeResponse detokenize(V1DetokenizeRequest request) {
        return this.rawClient.detokenize(request).body();
    }

    public V1DetokenizeResponse detokenize(V1DetokenizeRequest request, RequestOptions requestOptions) {
        return this.rawClient.detokenize(request, requestOptions).body();
    }

    public V1TokenizeResponse tokenize() {
        return this.rawClient.tokenize().body();
    }

    public V1TokenizeResponse tokenize(V1TokenizeRequest request) {
        return this.rawClient.tokenize(request).body();
    }

    public V1TokenizeResponse tokenize(V1TokenizeRequest request, RequestOptions requestOptions) {
        return this.rawClient.tokenize(request, requestOptions).body();
    }
    public V1DeleteTokenResponse deleteToken() {
        return this.rawClient.deleteToken().body();
    }

    public V1DeleteTokenResponse deleteToken(V1DeleteTokenRequest request) {
        return this.rawClient.deleteToken(request).body();
    }

    public V1DeleteTokenResponse deleteToken(V1DeleteTokenRequest request, RequestOptions requestOptions) {
        return this.rawClient.deleteToken(request, requestOptions).body();
    }
}
