/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH;

import com.skyflow.vaultLH.core.ClientOptions;
import com.skyflow.vaultLH.core.Suppliers;
import com.skyflow.vaultLH.resources.recordservice.AsyncRecordserviceClient;
import java.util.function.Supplier;

public class AsyncApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncRecordserviceClient> recordserviceClient;

    public AsyncApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.recordserviceClient = Suppliers.memoize(() -> new AsyncRecordserviceClient(clientOptions));
    }

    public AsyncRecordserviceClient recordservice() {
        return this.recordserviceClient.get();
    }

    public static AsyncApiClientBuilder builder() {
        return new AsyncApiClientBuilder();
    }
}
