/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.vaultLH.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExecuteQueryResponse.Builder.class)
public final class ExecuteQueryResponse {
    private final Optional<List<ExecuteQueryRecordResponse>> records;

    private final Map<String, Object> additionalProperties;

    private ExecuteQueryResponse(
            Optional<List<ExecuteQueryRecordResponse>> records, Map<String, Object> additionalProperties) {
        this.records = records;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Records corresponding to the specified query.
     */
    @JsonProperty("records")
    public Optional<List<ExecuteQueryRecordResponse>> getRecords() {
        return records;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ExecuteQueryResponse && equalTo((ExecuteQueryResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ExecuteQueryResponse other) {
        return records.equals(other.records);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.records);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ExecuteQueryRecordResponse>> records = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ExecuteQueryResponse other) {
            records(other.getRecords());
            return this;
        }

        /**
         * <p>Records corresponding to the specified query.</p>
         */
        @JsonSetter(value = "records", nulls = Nulls.SKIP)
        public Builder records(Optional<List<ExecuteQueryRecordResponse>> records) {
            this.records = records;
            return this;
        }

        public Builder records(List<ExecuteQueryRecordResponse> records) {
            this.records = Optional.ofNullable(records);
            return this;
        }

        public ExecuteQueryResponse build() {
            return new ExecuteQueryResponse(records, additionalProperties);
        }
    }
}
