/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.vaultLH.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokenizeResponse.Builder.class)
public final class TokenizeResponse {
    private final Optional<List<TokenizeResponseObject>> response;

    private final Map<String, Object> additionalProperties;

    private TokenizeResponse(
            Optional<List<TokenizeResponseObject>> response, Map<String, Object> additionalProperties) {
        this.response = response;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Tokenized data
     */
    @JsonProperty("response")
    public Optional<List<TokenizeResponseObject>> getResponse() {
        return response;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TokenizeResponse && equalTo((TokenizeResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TokenizeResponse other) {
        return response.equals(other.response);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.response);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<TokenizeResponseObject>> response = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TokenizeResponse other) {
            response(other.getResponse());
            return this;
        }

        /**
         * <p>Tokenized data</p>
         */
        @JsonSetter(value = "response", nulls = Nulls.SKIP)
        public Builder response(Optional<List<TokenizeResponseObject>> response) {
            this.response = response;
            return this;
        }

        public Builder response(List<TokenizeResponseObject> response) {
            this.response = Optional.ofNullable(response);
            return this;
        }

        public TokenizeResponse build() {
            return new TokenizeResponse(response, additionalProperties);
        }
    }
}
