/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.vaultLH.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokenGroupRedactions.Builder.class)
public final class TokenGroupRedactions {
    private final Optional<String> tokenGroupName;

    private final Optional<String> redaction;

    private final Map<String, Object> additionalProperties;

    private TokenGroupRedactions(
            Optional<String> tokenGroupName, Optional<String> redaction, Map<String, Object> additionalProperties) {
        this.tokenGroupName = tokenGroupName;
        this.redaction = redaction;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the token group to be redacted
     */
    @JsonProperty("tokenGroupName")
    public Optional<String> getTokenGroupName() {
        return tokenGroupName;
    }

    /**
     * @return Name of the redaction. Eg: <code>plain_text</code>, <code>redacted</code>, <code>mask1</code>
     */
    @JsonProperty("redaction")
    public Optional<String> getRedaction() {
        return redaction;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TokenGroupRedactions && equalTo((TokenGroupRedactions) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TokenGroupRedactions other) {
        return tokenGroupName.equals(other.tokenGroupName) && redaction.equals(other.redaction);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.tokenGroupName, this.redaction);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> tokenGroupName = Optional.empty();

        private Optional<String> redaction = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TokenGroupRedactions other) {
            tokenGroupName(other.getTokenGroupName());
            redaction(other.getRedaction());
            return this;
        }

        /**
         * <p>Name of the token group to be redacted</p>
         */
        @JsonSetter(value = "tokenGroupName", nulls = Nulls.SKIP)
        public Builder tokenGroupName(Optional<String> tokenGroupName) {
            this.tokenGroupName = tokenGroupName;
            return this;
        }

        public Builder tokenGroupName(String tokenGroupName) {
            this.tokenGroupName = Optional.ofNullable(tokenGroupName);
            return this;
        }

        /**
         * <p>Name of the redaction. Eg: <code>plain_text</code>, <code>redacted</code>, <code>mask1</code></p>
         */
        @JsonSetter(value = "redaction", nulls = Nulls.SKIP)
        public Builder redaction(Optional<String> redaction) {
            this.redaction = redaction;
            return this;
        }

        public Builder redaction(String redaction) {
            this.redaction = Optional.ofNullable(redaction);
            return this;
        }

        public TokenGroupRedactions build() {
            return new TokenGroupRedactions(tokenGroupName, redaction, additionalProperties);
        }
    }
}
