/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.vaultLH.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokenizeResponseObject.Builder.class)
public final class TokenizeResponseObject {
    private final Optional<Object> value;

    private final Optional<List<TokenizeResponseObjectToken>> tokens;

    private final Map<String, Object> additionalProperties;

    private TokenizeResponseObject(
            Optional<Object> value,
            Optional<List<TokenizeResponseObjectToken>> tokens,
            Map<String, Object> additionalProperties) {
        this.value = value;
        this.tokens = tokens;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("value")
    public Optional<Object> getValue() {
        return value;
    }

    /**
     * @return Token value
     */
    @JsonProperty("tokens")
    public Optional<List<TokenizeResponseObjectToken>> getTokens() {
        return tokens;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TokenizeResponseObject && equalTo((TokenizeResponseObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TokenizeResponseObject other) {
        return value.equals(other.value) && tokens.equals(other.tokens);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value, this.tokens);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Object> value = Optional.empty();

        private Optional<List<TokenizeResponseObjectToken>> tokens = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TokenizeResponseObject other) {
            value(other.getValue());
            tokens(other.getTokens());
            return this;
        }

        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public Builder value(Optional<Object> value) {
            this.value = value;
            return this;
        }

        public Builder value(Object value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        /**
         * <p>Token value</p>
         */
        @JsonSetter(value = "tokens", nulls = Nulls.SKIP)
        public Builder tokens(Optional<List<TokenizeResponseObjectToken>> tokens) {
            this.tokens = tokens;
            return this;
        }

        public Builder tokens(List<TokenizeResponseObjectToken> tokens) {
            this.tokens = Optional.ofNullable(tokens);
            return this;
        }

        public TokenizeResponseObject build() {
            return new TokenizeResponseObject(value, tokens, additionalProperties);
        }
    }
}
