/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH;

import com.skyflow.vaultLH.core.ClientOptions;
import com.skyflow.vaultLH.core.Suppliers;
import com.skyflow.vaultLH.resources.recordservice.RecordserviceClient;

import java.util.function.Supplier;

public class ApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<RecordserviceClient> recordserviceClient;

    public ApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.recordserviceClient = Suppliers.memoize(() -> new RecordserviceClient(clientOptions));
    }

    public RecordserviceClient recordservice() {
        return this.recordserviceClient.get();
    }

    public static ApiClientBuilder builder() {
        return new ApiClientBuilder();
    }
}
