/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.common.resources.authentication;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.skyflow.common.core.ApiClientApiException;
import com.skyflow.common.core.ApiClientException;
import com.skyflow.common.core.ApiClientHttpResponse;
import com.skyflow.common.core.ClientOptions;
import com.skyflow.common.core.MediaTypes;
import com.skyflow.common.core.ObjectMappers;
import com.skyflow.common.core.RequestOptions;
import com.skyflow.common.errors.BadRequestError;
import com.skyflow.common.errors.NotFoundError;
import com.skyflow.common.errors.UnauthorizedError;
import com.skyflow.common.resources.authentication.requests.V1GetAuthTokenRequest;
import com.skyflow.common.types.V1GetAuthTokenResponse;
import java.io.IOException;
import java.util.Map;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawAuthenticationClient {
    protected final ClientOptions clientOptions;

    public RawAuthenticationClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * <p>&lt;p&gt;Generates a Bearer Token to authenticate with Skyflow. This method doesn't require the &lt;code&gt;Authorization&lt;/code&gt; header.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Note:&lt;/b&gt; For recommended ways to authenticate, see &lt;a href='/api-authentication/'&gt;API authentication&lt;/a&gt;.&lt;/p&gt;</p>
     */
    public ApiClientHttpResponse<V1GetAuthTokenResponse> authenticationServiceGetAuthToken(
            V1GetAuthTokenRequest request) {
        return authenticationServiceGetAuthToken(request, null);
    }

    /**
     * <p>&lt;p&gt;Generates a Bearer Token to authenticate with Skyflow. This method doesn't require the &lt;code&gt;Authorization&lt;/code&gt; header.&lt;/p&gt;&lt;p&gt;&lt;b&gt;Note:&lt;/b&gt; For recommended ways to authenticate, see &lt;a href='/api-authentication/'&gt;API authentication&lt;/a&gt;.&lt;/p&gt;</p>
     */
    public ApiClientHttpResponse<V1GetAuthTokenResponse> authenticationServiceGetAuthToken(
            V1GetAuthTokenRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/auth/sa/oauth/token")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ApiClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new ApiClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), V1GetAuthTokenResponse.class),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, new TypeReference<Map<String, Object>>() {}),
                                response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, new TypeReference<Map<String, Object>>() {}),
                                response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, new TypeReference<Map<String, Object>>() {}),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            throw new ApiClientApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new ApiClientException("Network error executing HTTP request", e);
        }
    }
}
