/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.resources.recordservice;

import com.skyflow.vaultLH.core.ClientOptions;
import com.skyflow.vaultLH.core.RequestOptions;
import com.skyflow.vaultLH.resources.recordservice.requests.*;
import com.skyflow.vaultLH.types.*;

import java.util.concurrent.CompletableFuture;

public class AsyncRecordserviceClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawRecordserviceClient rawClient;

    public AsyncRecordserviceClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRecordserviceClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRecordserviceClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Executes a query on the specified vault.
     */
    public CompletableFuture<ExecuteQueryResponse> executequery() {
        return this.rawClient.executequery().thenApply(response -> response.body());
    }

    /**
     * Executes a query on the specified vault.
     */
    public CompletableFuture<ExecuteQueryResponse> executequery(ExecuteQueryRequest request) {
        return this.rawClient.executequery(request).thenApply(response -> response.body());
    }

    /**
     * Executes a query on the specified vault.
     */
    public CompletableFuture<ExecuteQueryResponse> executequery(
            ExecuteQueryRequest request, RequestOptions requestOptions) {
        return this.rawClient.executequery(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteResponse> delete() {
        return this.rawClient.delete().thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteResponse> delete(DeleteRequest request) {
        return this.rawClient.delete(request).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteResponse> delete(DeleteRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetResponse> get() {
        return this.rawClient.get().thenApply(response -> response.body());
    }

    public CompletableFuture<GetResponse> get(GetRequest request) {
        return this.rawClient.get(request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetResponse> get(GetRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<InsertResponse> insert() {
        return this.rawClient.insert().thenApply(response -> response.body());
    }

    public CompletableFuture<InsertResponse> insert(InsertRequest request) {
        return this.rawClient.insert(request).thenApply(response -> response.body());
    }

    public CompletableFuture<InsertResponse> insert(InsertRequest request, RequestOptions requestOptions) {
        return this.rawClient.insert(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<UpdateResponse> update() {
        return this.rawClient.update().thenApply(response -> response.body());
    }

    public CompletableFuture<UpdateResponse> update(UpdateRequest request) {
        return this.rawClient.update(request).thenApply(response -> response.body());
    }

    public CompletableFuture<UpdateResponse> update(UpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteTokenResponse> deletetoken() {
        return this.rawClient.deletetoken().thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteTokenResponse> deletetoken(DeleteTokenRequest request) {
        return this.rawClient.deletetoken(request).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteTokenResponse> deletetoken(
            DeleteTokenRequest request, RequestOptions requestOptions) {
        return this.rawClient.deletetoken(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DetokenizeResponse> detokenize() {
        return this.rawClient.detokenize().thenApply(response -> response.body());
    }

    public CompletableFuture<DetokenizeResponse> detokenize(DetokenizeRequest request) {
        return this.rawClient.detokenize(request).thenApply(response -> response.body());
    }

    public CompletableFuture<DetokenizeResponse> detokenize(DetokenizeRequest request, RequestOptions requestOptions) {
        return this.rawClient.detokenize(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<TokenizeResponse> tokenize() {
        return this.rawClient.tokenize().thenApply(response -> response.body());
    }

    public CompletableFuture<TokenizeResponse> tokenize(TokenizeRequest request) {
        return this.rawClient.tokenize(request).thenApply(response -> response.body());
    }

    public CompletableFuture<TokenizeResponse> tokenize(TokenizeRequest request, RequestOptions requestOptions) {
        return this.rawClient.tokenize(request, requestOptions).thenApply(response -> response.body());
    }
}
