/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.vaultLH.resources.recordservice;

import com.skyflow.vaultLH.core.ClientOptions;
import com.skyflow.vaultLH.core.RequestOptions;
import com.skyflow.vaultLH.resources.recordservice.requests.*;
import com.skyflow.vaultLH.types.*;

public class RecordserviceClient {
    protected final ClientOptions clientOptions;

    private final RawRecordserviceClient rawClient;

    public RecordserviceClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawRecordserviceClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawRecordserviceClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Executes a query on the specified vault.
     */
    public ExecuteQueryResponse executequery() {
        return this.rawClient.executequery().body();
    }

    /**
     * Executes a query on the specified vault.
     */
    public ExecuteQueryResponse executequery(ExecuteQueryRequest request) {
        return this.rawClient.executequery(request).body();
    }

    /**
     * Executes a query on the specified vault.
     */
    public ExecuteQueryResponse executequery(ExecuteQueryRequest request, RequestOptions requestOptions) {
        return this.rawClient.executequery(request, requestOptions).body();
    }

    public DeleteResponse delete() {
        return this.rawClient.delete().body();
    }

    public DeleteResponse delete(DeleteRequest request) {
        return this.rawClient.delete(request).body();
    }

    public DeleteResponse delete(DeleteRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(request, requestOptions).body();
    }

    public GetResponse get() {
        return this.rawClient.get().body();
    }

    public GetResponse get(GetRequest request) {
        return this.rawClient.get(request).body();
    }

    public GetResponse get(GetRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(request, requestOptions).body();
    }

    public InsertResponse insert() {
        return this.rawClient.insert().body();
    }

    public InsertResponse insert(InsertRequest request) {
        return this.rawClient.insert(request).body();
    }

    public InsertResponse insert(InsertRequest request, RequestOptions requestOptions) {
        return this.rawClient.insert(request, requestOptions).body();
    }

    public UpdateResponse update() {
        return this.rawClient.update().body();
    }

    public UpdateResponse update(UpdateRequest request) {
        return this.rawClient.update(request).body();
    }

    public UpdateResponse update(UpdateRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(request, requestOptions).body();
    }

    public DeleteTokenResponse deletetoken() {
        return this.rawClient.deletetoken().body();
    }

    public DeleteTokenResponse deletetoken(DeleteTokenRequest request) {
        return this.rawClient.deletetoken(request).body();
    }

    public DeleteTokenResponse deletetoken(DeleteTokenRequest request, RequestOptions requestOptions) {
        return this.rawClient.deletetoken(request, requestOptions).body();
    }

    public DetokenizeResponse detokenize() {
        return this.rawClient.detokenize().body();
    }

    public DetokenizeResponse detokenize(DetokenizeRequest request) {
        return this.rawClient.detokenize(request).body();
    }

    public DetokenizeResponse detokenize(DetokenizeRequest request, RequestOptions requestOptions) {
        return this.rawClient.detokenize(request, requestOptions).body();
    }

    public TokenizeResponse tokenize() {
        return this.rawClient.tokenize().body();
    }

    public TokenizeResponse tokenize(TokenizeRequest request) {
        return this.rawClient.tokenize(request).body();
    }

    public TokenizeResponse tokenize(TokenizeRequest request, RequestOptions requestOptions) {
        return this.rawClient.tokenize(request, requestOptions).body();
    }
}
