name: Endor Labs Scan Java Project

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: "The version of Java to be used for build"
        default: "8.0.422"
        required: true

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ github.event.inputs.java_version }}

      - name: Create env
        id: create-env
        run: |
          touch .env
          echo SKYFLOW_CREDENTIALS=${{ secrets.SKYFLOW_CREDENTIALS }} >> .env
          echo TEST_EXPIRED_TOKEN=${{ secrets.TEST_EXPIRED_TOKEN }} >> .env
          echo TEST_REUSABLE_TOKEN=${{ secrets.TEST_REUSABLE_TOKEN }} >> .env

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "credentials.json"
          json: ${{ secrets.TEST_CREDENTIALS_FILE_STRING }}

      - name: Compile Package
        run: mvn -B package -DTEST_VAULT_ID=${{ secrets.TEST_VAULT_ID }} -DTEST_VAULT_URL=${{ secrets.TEST_VAULT_URL }} -DTEST_SKYFLOW_ID=${{ secrets.TEST_SKYFLOW_ID }} -DTEST_TOKEN=${{ secrets.TEST_TOKEN }} -DTEST_CREDENTIALS=${{ secrets.TEST_CREDENTIALS_FILE_STRING }} -DTEST_EXPIRED_TOKEN=${{ secrets.TEST_EXPIRED_TOKEN }} -DTEST_REUSABLE_TOKEN=${{ secrets.TEST_REUSABLE_TOKEN }} -DSKYFLOW_CREDENTIALS=${{ secrets.SKYFLOW_CREDENTIALS }} -f pom.xml

      - name: Endor Labs SCA Scan
        uses: endorlabs/github-action@main
        with:
          namespace: "skyflow"
          api: "https://api.endorlabs.com"
          pr: false
          enable_github_action_token: true
          scan_dependencies: true
          additional_args: "--as-default-branch --call-graph-languages=java"
