name: Public release
on:
  push:
    tags: '*.*.*'
jobs:
  build-and-deploy:
    uses: ./.github/workflows/shared-build-and-deploy.yml
    with:
      ref: ${{ github.ref_name }}
      server-id: ossrh
      profile: maven-central
      tag: 'public'
    secrets:
      server-username: ${{ secrets.OSSRH_USERNAME }}
      server-password: ${{ secrets.OSSRH_PASSWORD }}
      gpg-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      skyflow-credentials: ${{ secrets.SKYFLOW_CREDENTIALS }} >> .env
      test-expired-token: ${{ secrets.TEST_EXPIRED_TOKEN }} >> .env
      test-reusable-token: ${{ secrets.TEST_REUSABLE_TOKEN }} >> .env
