name: Publish package to the Maven Central Repository
on:
  push:
    tags: '*.*.*'
jobs:
  build-and-deploy:
    uses: ./.github/workflows/shared-build-and-deploy.yml
    with:
      ref: ${{ github.ref_name }}
      is-internal: false
      server-id: ossrh
      profile: maven-central
    secrets:
      server-username: ${{ secrets.OSSRH_USERNAME }}
      server-password: ${{ secrets.OSSRH_PASSWORD }}
      gpg-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      