name: Publish package to the Maven Central Repository
on:
  push:
    tags: '*.*.*'
jobs:
  build-and-deploy:
    uses: ./.github/workflows/shared-build-and-deploy.yml
    with:
      ref: ${{ github.ref_name }}
      is-internal: false
