/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokenizeResponseObjectToken.Builder.class)
public final class TokenizeResponseObjectToken {
    private final Optional<String> tokenGroupName;

    private final Optional<String> token;

    private final Optional<String> error;

    private final Optional<Integer> httpCode;

    private final Map<String, Object> additionalProperties;

    private TokenizeResponseObjectToken(
            Optional<String> tokenGroupName,
            Optional<String> token,
            Optional<String> error,
            Optional<Integer> httpCode,
            Map<String, Object> additionalProperties) {
        this.tokenGroupName = tokenGroupName;
        this.token = token;
        this.error = error;
        this.httpCode = httpCode;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Token group Name
     */
    @JsonProperty("tokenGroupName")
    public Optional<String> getTokenGroupName() {
        return tokenGroupName;
    }

    /**
     * @return Token value
     */
    @JsonProperty("token")
    public Optional<String> getToken() {
        return token;
    }

    /**
     * @return Error if tokenization failed
     */
    @JsonProperty("error")
    public Optional<String> getError() {
        return error;
    }

    /**
     * @return HTTP status code of the response
     */
    @JsonProperty("httpCode")
    public Optional<Integer> getHttpCode() {
        return httpCode;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TokenizeResponseObjectToken && equalTo((TokenizeResponseObjectToken) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TokenizeResponseObjectToken other) {
        return tokenGroupName.equals(other.tokenGroupName)
                && token.equals(other.token)
                && error.equals(other.error)
                && httpCode.equals(other.httpCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.tokenGroupName, this.token, this.error, this.httpCode);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> tokenGroupName = Optional.empty();

        private Optional<String> token = Optional.empty();

        private Optional<String> error = Optional.empty();

        private Optional<Integer> httpCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TokenizeResponseObjectToken other) {
            tokenGroupName(other.getTokenGroupName());
            token(other.getToken());
            error(other.getError());
            httpCode(other.getHttpCode());
            return this;
        }

        @JsonSetter(value = "tokenGroupName", nulls = Nulls.SKIP)
        public Builder tokenGroupName(Optional<String> tokenGroupName) {
            this.tokenGroupName = tokenGroupName;
            return this;
        }

        public Builder tokenGroupName(String tokenGroupName) {
            this.tokenGroupName = Optional.ofNullable(tokenGroupName);
            return this;
        }

        @JsonSetter(value = "token", nulls = Nulls.SKIP)
        public Builder token(Optional<String> token) {
            this.token = token;
            return this;
        }

        public Builder token(String token) {
            this.token = Optional.ofNullable(token);
            return this;
        }

        @JsonSetter(value = "error", nulls = Nulls.SKIP)
        public Builder error(Optional<String> error) {
            this.error = error;
            return this;
        }

        public Builder error(String error) {
            this.error = Optional.ofNullable(error);
            return this;
        }

        @JsonSetter(value = "httpCode", nulls = Nulls.SKIP)
        public Builder httpCode(Optional<Integer> httpCode) {
            this.httpCode = httpCode;
            return this;
        }

        public Builder httpCode(Integer httpCode) {
            this.httpCode = Optional.ofNullable(httpCode);
            return this;
        }

        public TokenizeResponseObjectToken build() {
            return new TokenizeResponseObjectToken(tokenGroupName, token, error, httpCode, additionalProperties);
        }
    }
}
