/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1ColumnRedactions.Builder.class)
public final class V1ColumnRedactions {
    private final Optional<String> columnName;

    private final Optional<String> redaction;

    private final Map<String, Object> additionalProperties;

    private V1ColumnRedactions(
            Optional<String> columnName, Optional<String> redaction, Map<String, Object> additionalProperties) {
        this.columnName = columnName;
        this.redaction = redaction;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the column to be redacted
     */
    @JsonProperty("columnName")
    public Optional<String> getColumnName() {
        return columnName;
    }

    /**
     * @return Name of the redaction. Eg: <code>plain_text</code>, <code>redacted</code>, <code>mask1</code>
     */
    @JsonProperty("redaction")
    public Optional<String> getRedaction() {
        return redaction;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1ColumnRedactions && equalTo((V1ColumnRedactions) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1ColumnRedactions other) {
        return columnName.equals(other.columnName) && redaction.equals(other.redaction);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.columnName, this.redaction);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> columnName = Optional.empty();

        private Optional<String> redaction = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(V1ColumnRedactions other) {
            columnName(other.getColumnName());
            redaction(other.getRedaction());
            return this;
        }

        @JsonSetter(value = "columnName", nulls = Nulls.SKIP)
        public Builder columnName(Optional<String> columnName) {
            this.columnName = columnName;
            return this;
        }

        public Builder columnName(String columnName) {
            this.columnName = Optional.ofNullable(columnName);
            return this;
        }

        @JsonSetter(value = "redaction", nulls = Nulls.SKIP)
        public Builder redaction(Optional<String> redaction) {
            this.redaction = redaction;
            return this;
        }

        public Builder redaction(String redaction) {
            this.redaction = Optional.ofNullable(redaction);
            return this;
        }

        public V1ColumnRedactions build() {
            return new V1ColumnRedactions(columnName, redaction, additionalProperties);
        }
    }
}
