/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1DeleteTokenResponseObject.Builder.class)
public final class V1DeleteTokenResponseObject {
    private final Optional<String> value;

    private final Optional<String> error;

    private final Optional<Integer> httpCode;

    private final Map<String, Object> additionalProperties;

    private V1DeleteTokenResponseObject(
            Optional<String> value,
            Optional<String> error,
            Optional<Integer> httpCode,
            Map<String, Object> additionalProperties) {
        this.value = value;
        this.error = error;
        this.httpCode = httpCode;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Token value
     */
    @JsonProperty("value")
    public Optional<String> getValue() {
        return value;
    }

    /**
     * @return Error if deletion failed
     */
    @JsonProperty("error")
    public Optional<String> getError() {
        return error;
    }

    /**
     * @return HTTP status code of the response
     */
    @JsonProperty("httpCode")
    public Optional<Integer> getHttpCode() {
        return httpCode;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1DeleteTokenResponseObject && equalTo((V1DeleteTokenResponseObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1DeleteTokenResponseObject other) {
        return value.equals(other.value) && error.equals(other.error) && httpCode.equals(other.httpCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.value, this.error, this.httpCode);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> value = Optional.empty();

        private Optional<String> error = Optional.empty();

        private Optional<Integer> httpCode = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(V1DeleteTokenResponseObject other) {
            value(other.getValue());
            error(other.getError());
            httpCode(other.getHttpCode());
            return this;
        }

        @JsonSetter(value = "value", nulls = Nulls.SKIP)
        public Builder value(Optional<String> value) {
            this.value = value;
            return this;
        }

        public Builder value(String value) {
            this.value = Optional.ofNullable(value);
            return this;
        }

        @JsonSetter(value = "error", nulls = Nulls.SKIP)
        public Builder error(Optional<String> error) {
            this.error = error;
            return this;
        }

        public Builder error(String error) {
            this.error = Optional.ofNullable(error);
            return this;
        }

        @JsonSetter(value = "httpCode", nulls = Nulls.SKIP)
        public Builder httpCode(Optional<Integer> httpCode) {
            this.httpCode = httpCode;
            return this;
        }

        public Builder httpCode(Integer httpCode) {
            this.httpCode = Optional.ofNullable(httpCode);
            return this;
        }

        public V1DeleteTokenResponseObject build() {
            return new V1DeleteTokenResponseObject(value, error, httpCode, additionalProperties);
        }
    }
}
