/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1ExecuteQueryRecordResponse.Builder.class)
public final class V1ExecuteQueryRecordResponse {
    private final Optional<Map<String, Object>> data;

    private final Map<String, Object> additionalProperties;

    private V1ExecuteQueryRecordResponse(Optional<Map<String, Object>> data, Map<String, Object> additionalProperties) {
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Fields and values for the record. For example, <code>{'field_1':'value_1', 'field_2':'value_2'}</code>.
     */
    @JsonProperty("data")
    public Optional<Map<String, Object>> getData() {
        return data;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1ExecuteQueryRecordResponse && equalTo((V1ExecuteQueryRecordResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1ExecuteQueryRecordResponse other) {
        return data.equals(other.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.data);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Map<String, Object>> data = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(V1ExecuteQueryRecordResponse other) {
            data(other.getData());
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(Optional<Map<String, Object>> data) {
            this.data = data;
            return this;
        }

        public Builder data(Map<String, Object> data) {
            this.data = Optional.ofNullable(data);
            return this;
        }

        public V1ExecuteQueryRecordResponse build() {
            return new V1ExecuteQueryRecordResponse(data, additionalProperties);
        }
    }
}
