/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1TokenizeResponse.Builder.class)
public final class V1TokenizeResponse {
    private final Optional<List<V1TokenizeResponseObject>> response;

    private final Map<String, Object> additionalProperties;

    private V1TokenizeResponse(
            Optional<List<V1TokenizeResponseObject>> response, Map<String, Object> additionalProperties) {
        this.response = response;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Tokenized data
     */
    @JsonProperty("response")
    public Optional<List<V1TokenizeResponseObject>> getResponse() {
        return response;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1TokenizeResponse && equalTo((V1TokenizeResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1TokenizeResponse other) {
        return response.equals(other.response);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.response);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<V1TokenizeResponseObject>> response = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(V1TokenizeResponse other) {
            response(other.getResponse());
            return this;
        }

        @JsonSetter(value = "response", nulls = Nulls.SKIP)
        public Builder response(Optional<List<V1TokenizeResponseObject>> response) {
            this.response = response;
            return this;
        }

        public Builder response(List<V1TokenizeResponseObject> response) {
            this.response = Optional.ofNullable(response);
            return this;
        }

        public V1TokenizeResponse build() {
            return new V1TokenizeResponse(response, additionalProperties);
        }
    }
}
