/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.skyflow.api.types;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.skyflow.api.core.ObjectMappers;

import java.util.*;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = V1UpdateResponse.Builder.class)
public final class V1UpdateResponse {
    private final Optional<List<V1RecordResponseObject>> records;

    private final Map<String, Object> additionalProperties;

    private V1UpdateResponse(Optional<List<V1RecordResponseObject>> records, Map<String, Object> additionalProperties) {
        this.records = records;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return List of updated records with skyflow ID, tokens, data, and any partial errors
     */
    @JsonProperty("records")
    public Optional<List<V1RecordResponseObject>> getRecords() {
        return records;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof V1UpdateResponse && equalTo((V1UpdateResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(V1UpdateResponse other) {
        return records.equals(other.records);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.records);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<V1RecordResponseObject>> records = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(V1UpdateResponse other) {
            records(other.getRecords());
            return this;
        }

        @JsonSetter(value = "records", nulls = Nulls.SKIP)
        public Builder records(Optional<List<V1RecordResponseObject>> records) {
            this.records = records;
            return this;
        }

        public Builder records(List<V1RecordResponseObject> records) {
            this.records = Optional.ofNullable(records);
            return this;
        }

        public V1UpdateResponse build() {
            return new V1UpdateResponse(records, additionalProperties);
        }
    }
}
